### ISSUE TITLE
the problem about Escape Installation

### ISSUE THREAD

**Issue by 478463266** [hsnlab/escape#3]
hello, I would like to do some research on the Escape platform, but after I install it on my desktop as illustrated on the web https://sb.tmit.bme.hu/escape/, I meet some problems
When I input the code" ./escape.py -df -s examples/escape-mn-req.nffg ", it shows as below:
[D][boot                   ] Not launching of_01
[D][core                   ] ESCAPEv2 going up...
[D][core                   ] Running on CPython (2.7.13/Oct 30 2017 14:22:29)
[D][core                   ] Platform is Linux-4.10.0-37-generic-x86_64-with-debian-stretch-sid
Traceback (most recent call last):
  File "/home/renwei/escape/pox/pox/boot.py", line 536, in boot
    core.goUp()
  File "/home/renwei/escape/pox/pox/core.py", line 375, in goUp
    self.raiseEvent(GoingUpEvent())
  File "/home/renwei/escape/pox/pox/lib/revent/revent.py", line 291, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/renwei/escape/pox/pox/lib/revent/revent.py", line 166, in _invoke
    return handler(self, *args, **kw)
  File "/home/renwei/escape/pox/ext/ESCAPE.py", line 47, in _start_components
    from infrastructure import launch
  File "/home/renwei/escape/escape/infrastructure.py", line 24, in <module>
    from escape.infr.il_API import InfrastructureLayerAPI
  File "/home/renwei/escape/escape/escape/infr/il_API.py", line 19, in <module>
    from escape.infr.topology import ESCAPENetworkBuilder
  File "/home/renwei/escape/escape/escape/infr/topology.py", line 24, in <module>
    from mininet.node import RemoteController, RemoteSwitch
ImportError: cannot import name RemoteSwitch

**Comment by czeni** [comment]
Issue is fixed in commit: bd62de21029507d771d88cec9750ddc2dda1935a
